INTERACTION_CHAINS_ROOT = "data/graphs/interaction_chains"
DEFAULT_INTERACTION_CHAINS_PATH = f"{INTERACTION_CHAINS_ROOT}/neutral_relay"
DEFAULT_INTERACTION_GRAPH_PATH = f"{DEFAULT_INTERACTION_CHAINS_PATH}/01_nnnn.json"
DEFAULT_INTERACTION_CHAIN_CODES = (
    "NNNN",
    "CCCC",
    "PPPP",
    "DDDD",
    "CCPP",
    "PPCC",
    "DDNN",
    "NNDD",
)
